version: '3'

services:
  app:
    image: ykamoge/docker-textlint
    container_name: docker-textlint
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/app/
    environment:
      TZ: Asia/Tokyo

